# Reload config quickly
bind r source-file ~/.tmux.conf \; display-message "config reloaded ✔"

set -g status-style "bg=color150,fg=black"
set -g status-left "[ #S ] "

setw -g window-status-style "fg=black"
setw -g window-status-current-style "bold"

set -g status-interval 30

set -g status-right '%H:%M #(bash $HOME/.dotfiles/.dotfiles-modules/terminal/tmux-battery.sh)'
