#! /bin/bash

dotfiles_config="$HOME/.dotfiles-config" 
touch $dotfiles_config

declare -a config_modules=()

if [[ -f "$dotfiles_config" ]]; then
  source "$dotfiles_config"
  # provides $config_modules
fi

echo '++++++++++++++++'
echo 'DOTFILES INSTALL'
echo '++++++++++++++++'

source_file="$HOME/.dotfiles-source"
source_command="source $source_file"

if ! grep -Fxq "$source_command" "$HOME/.bashrc"; then
  echo "$source_command" >> "$HOME/.bashrc"
fi

cat <<'SOURCE' > $source_file
# THIS FILE IS GENERATED BY ~/.dotfiles-modules/install.sh
# ---
# DO NOT TRACK IN GIT
# ---
# DO NOT MANUALLY EDIT
#

SOURCE

declare -A ROOT_COMMANDS
as_root() {
  module=$(basename $(dirname "${BASH_SOURCE[1]}"))
  
  code=$1
  if [ -z "$code" ]; then
    read code
  fi

  ROOT_COMMANDS[$module]=$(printf '%q' "$code")

  echo "  > Added commands to run as root"
}

modules_root="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/.dotfiles-modules"

VALID_MODULES=( $modules_root/*/ )
VALID_MODULES=( "${VALID_MODULES[@]%/}" )
VALID_MODULES=( "${VALID_MODULES[@]#"$modules_root/"}" )

requested_modules=($@)

declare -A in_VALID_MODULES=(); for x in "${VALID_MODULES[@]}"; do in_VALID_MODULES["$x"]=1; done
declare -A found=(); invalid=()
for x in "${requested_modules[@]}"; do
  if [[ -z ${in_VALID_MODULES[$x]+_} && -z ${found[$x]+_} ]]; then
    found["$x"]=1
    invalid+=("$x")
  fi
done

if (( ${#invalid[@]} > 0 )); then
    echo ''
    echo 'Invalid modules requested'
    printf "  %s\n"  "${invalid[@]}"
    exit 0
fi


if (( ${#requested_modules[@]} == 0 && ${#config_modules[@]} == 0)); then
  echo "Using all modules"

  # Use all modules by default, if none provided
  requested_modules=( "${VALID_MODULES[@]}" )
fi

if (( ${#config_modules[@]} != 0)); then
  if (( ${#requested_modules[@]} == 0 )); then
    echo "Using modules from config"
  else
    echo "Adding requested modules to config"
  fi
  
  # Load modules from config
  requested_modules+=("${config_modules[@]}")
fi

# Default
modules=('terminal')

# Requested
modules+=("${requested_modules[@]}")

# Keep only unique values
mapfile -t modules < <(printf '%s\n' "${modules[@]}" | sort -u)

echo "[ ${modules[@]} ]"

# cli-apps desktop-apps dotfiles git gnome node php ruby vbox-vagrant wacom
# modules+=(cli-apps desktop-apps dotfiles git gnome node php ruby vbox-vagrant wacom)
#
# modules+=(cli-apps)
# modules+=(desktop-apps)
# modules+=(dotfiles)
# modules+=(git)
# modules+=(gnome)
# modules+=(node)
# modules+=(php)
# modules+=(ruby)
# modules+=(vbox-vagrant)
# modules+=(wacom)

modules_count=${#modules[@]}
index=0

for module in "${modules[@]}"; do
  ((index++))

  echo ''
  echo "( $index / $modules_count ) Processing [$module]"

  module_directory="$modules_root/$module"

  #
  # Source
  #
  module_source_file="$module_directory/source.sh"

  if [[ -f "$module_source_file" ]]; then
    module_source_command="source $module_source_file"

    if ! grep -Fxq "$module_source_command" "$source_file"; then
      echo "  Applying source"

      echo "$module_source_command" >> "$source_file"
    fi

  fi

  #
  # Install
  #
  module_install_file="$module_directory/install.sh"

  if [[ -f "$module_install_file" ]]; then
    echo "  Running install"

    source "$module_install_file"
  fi
done

echo ''
echo 'Root needed for further configuration'

read -r -d '' root_needed <<'_'
  eval "$param"

  root_modules_count=${#ROOT_COMMANDS[@]}
  root_index=0

  apt-get update &>>"$VERBOSE_OUTPUT"
  apt-get upgrade -y &>>"$VERBOSE_OUTPUT"

  for module in $(printf "%s\n" "${!ROOT_COMMANDS[@]}" | LC_ALL=C sort); do
    ((root_index++))

    echo ''
    echo "( $root_index / $root_modules_count ) Running as root [$module]"
    
    # eval to var first to handle escaped space \
    # from printf %q in as_root() to allow associative array transfert
    eval "code=${ROOT_COMMANDS[$module]}"
    code="${code//apt /apt -y }"
    code="${code//apt-get/apt-get -y}"

    export DEBIAN_FRONTEND=noninteractive
    eval "$code" &>>"$VERBOSE_OUTPUT"
  done
_

output="${VERBOSE:-'/dev/null'}"

su -lc "VERBOSE_OUTPUT="$output"; param='$(declare -p ROOT_COMMANDS)'; eval '$root_needed'"


if (( ${#config_modules[@]} == 0 )); then
  # First time only

  if [[ -n "$(which gnome-shell)" ]]; then
    echo ''
    echo 'Might need to reload Gnome session'

    echo "su -lc 'systemctl restart gdm'"
  fi

  if [[ -n "$(apt list --installed 2>/dev/null | grep ufw)" ]]; then
    echo ''
    echo 'Enable firewall'

    echo "su -lc 'ufw enable'"
  fi

  if [[ -z "$(git config --global user.email)" ]]; then
    echo ''
    echo 'Git config'

    echo 'git config --global user.email <email>'
    echo 'git config --global user.name <name>'
  fi

  if ! [[ -f "$HOME/.ssh/id_rsa" ]]; then
    echo ''
    echo 'SSH RSA'

    ssh-keygen -f $HOME/.ssh/id_rsa -P ""
    eval `ssh-agent`
    ssh-add $HOME/.ssh/id_rsa
  fi
fi

config_modules=( "${modules[@]}" )
config_modules_declare="$(declare -p config_modules)"

if grep -Fq "config_modules" $dotfiles_config; then
  sed -i "/config_modules/s/^.*$/$config_modules_declare/" "$dotfiles_config"
else
  echo "$config_modules_declare" >> "$dotfiles_config"
fi

source $HOME/.bashrc

echo ''
echo '~~~~'
echo 'DONE'
echo '~~~~'
