set nocompatible

set splitbelow
set splitright
set tabpagemax=9999

syntax on
set autoindent
set backspace=indent,eol,start
" filetype plugin indent on
set shiftwidth=2
set tabstop=2
set expandtab

set path+=**
set wildmenu

set hlsearch
set incsearch
set ignorecase
set smartcase

set noswapfile
set hidden

set cursorline
set number
set relativenumber

set statusline=2
colorscheme onehalflight
set t_Co=256

let &t_SI = "\e[5 q"
let &t_EI = "\e[2 q"

map <leader>h :noh<CR>

command! CDC lcd %:p:h

let g:user_emmet_leader_key = ','
let g:user_emmet_mode='a'

nnoremap '' :FZF<cr>

function! SetTheme()
  let g:gnome_theme = system('gsettings get org.gnome.desktop.interface color-scheme')

  if g:gnome_theme =~ 'prefer-dark'
      colorscheme onehalfdark
  else
      colorscheme onehalflight
  endif
endfunction

call SetTheme()
autocmd FocusGained * :call SetTheme()
" too agressive
" autocmd SafeState * :call SetTheme()
