#! /bin/bash

echo "++++++++++++++++"
echo "DOTFILES INSTALL"
echo "++++++++++++++++"

source_file="$HOME/.dotfiles-source"
source_command="source $source_file"

if ! grep -Fxq "$source_command" "$HOME/.bashrc"; then
  echo "$source_command" >> "$HOME/.bashrc"
fi

cat <<'SOURCE' > $source_file
# THIS FILE IS GENERATED BY ~/.dotfiles-modules/install.sh
# ---
# DO NOT TRACK IN GIT
# ---
# DO NOT MANUALLY EDIT
#

SOURCE

modules=("dotfiles" "gnome-extensions")

for module in "${modules[@]}"; do

  module_directory="$HOME/.dotfiles-modules/$module"

  #
  # Source
  #
  module_source_file="$module_directory/source.sh"

  if [[ -f "$module_source_file" ]]; then

    module_source_command="source $module_source_file"

    if ! grep -Fxq "$module_source_command" "$source_file"; then
      echo "$module_source_command" >> "$source_file"
    fi

  fi

  #
  # Install
  #
  module_install_file="$module_directory/install.sh"

  if [[ -f "$module_install_file" ]]; then
    bash "$module_install_file"
  fi

done

echo '~~~~'
echo 'DONE'
echo '~~~~'

echo 'Reload Gnome session'
echo 'su -lc 'systemctl restart gdm'
