#! /bin/bash

echo "++++++++++++++++"
echo "DOTFILES INSTALL"
echo "++++++++++++++++"

source_file="$HOME/.dotfiles-source"
source_command="source $source_file"

if ! grep -Fxq "$source_command" "$HOME/.bashrc"; then
  echo "$source_command" >> "$HOME/.bashrc"
fi

cat <<'SOURCE' > $source_file
# THIS FILE IS GENERATED BY ~/.dotfiles-modules/install.sh
# ---
# DO NOT TRACK IN GIT
# ---
# DO NOT MANUALLY EDIT
#

SOURCE

# declare -A SOURCE_COMMANDS
# declare -A INSTALL_COMMANDS

declare -A ROOT_COMMANDS
as_root() {
  module=$(basename $(dirname "${BASH_SOURCE[1]}"))
  ROOT_COMMANDS[$module]="$1"
  echo "  > Added commands to run as root"
}

# default modules
modules=('dotfiles' 'terminal' 'git')

# optional modules
modules+=('gnome-extensions')

for module in "${modules[@]}"; do

  echo "Processing [$module]"

  module_directory="$HOME/.dotfiles-modules/$module"

  #
  # Source
  #
  module_source_file="$module_directory/source.sh"

  if [[ -f "$module_source_file" ]]; then
    module_source_command="source $module_source_file"

    if ! grep -Fxq "$module_source_command" "$source_file"; then
      echo "  Applying source"

      echo "$module_source_command" >> "$source_file"
    fi

  fi

  #
  # Install
  #
  module_install_file="$module_directory/install.sh"

  if [[ -f "$module_install_file" ]]; then
    echo "  Running install"

    source "$module_install_file"
  fi
done

echo ''
echo 'Root needed for further configuration'

read -r -d '' root_needed <<'_'
  eval "'"$param"'"

  for module in \"${!ROOT_COMMANDS[@]}\"; do
    echo \"[$module]\"

    if [[ -v ROOT_COMMANDS["$module"] ]]; then
      echo \"[$module]\"
      echo \"> Rooting...\"
    fi
  done
_

param=$(declare -p ROOT_COMMANDS)

su -lc "param='$param'; eval '$root_needed'"

echo '~~~~'
echo 'DONE'
echo '~~~~'

echo 'Reload Gnome session'
echo "su -lc 'systemctl restart gdm'"
