on:
  push:
    branches:
    - main
jobs:
  archive:
    name: make tar archive
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Compute short sha
        run: echo "short_sha=${GITHUB_SHA::7}" >> $GITHUB_ENV
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.short_sha }}
